### ISSUE TITLE
Cannot install on MacOS

### ISSUE THREAD

**Issue by pavpanchekha** [skapfer/rubber#1]
I'm trying to install current master (596dcd6c097864f70f5231069733e6f747046301) on MacOS 10.15.4 with Python 3.7.3. However, when I run `python3 setup.py install`, I get:

```
running install
running build
running build_py
Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    "tar": tar,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 140, in run
    distutils.command.install.install.run (self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 561, in run
    self.run_command('build')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 97, in run
    distutils.command.build.build.run (self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build_py.py", line 56, in finalize_options
    self.data_files = self.get_data_files()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build_py.py", line 116, in get_data_files
    file[plen:] for file in self.find_data_files(package, src_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/distutils/command/build_py.py", line 124, in find_data_files
    + self.package_data.get(package, []))
TypeError: can only concatenate list (not "tuple") to list
```

**Comment by skapfer** [comment]
Hey!

This repo is not really maintained any more. Have a look here: https://git.launchpad.net/rubber/commit/?id=a391fa26289a4baadc5028aad48f1453b0122c27

Cheers

Sebastian
